package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ApprovalDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "APPROVALDETAILS_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "APPROVALDETAILS_ID_GENERATOR", sequenceName = "APPROVALDETAILS_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Approval Status")
	private java.lang.String approvalStatus;

	@org.kie.api.definition.type.Label(value = "Remarks")
	private java.lang.String remarks;

	public ApprovalDetails() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getApprovalStatus() {
		return this.approvalStatus;
	}

	public void setApprovalStatus(java.lang.String approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	public java.lang.String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(java.lang.String remarks) {
		this.remarks = remarks;
	}

	public ApprovalDetails(java.lang.Long id, java.lang.String approvalStatus,
			java.lang.String remarks) {
		this.id = id;
		this.approvalStatus = approvalStatus;
		this.remarks = remarks;
	}

}