package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CurrentState implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "CURRENTSTATE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CURRENTSTATE_ID_GENERATOR", sequenceName = "CURRENTSTATE_ID_SEQ")
	private java.lang.Long id;

	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	@org.kie.api.definition.type.Label(value = "State Details")
	private java.util.HashMap<java.lang.String, com.ProcessDetails> stateDetails = new java.util.HashMap<>();

	@org.kie.api.definition.type.Label(value = "Temp")
	private java.lang.String temp;

	public CurrentState() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.util.HashMap<java.lang.String, com.ProcessDetails> getStateDetails() {
		return this.stateDetails;
	}

	public void setStateDetails(
			java.util.HashMap<java.lang.String, com.ProcessDetails> stateDetails) {
		this.stateDetails = stateDetails;
	}

	public CurrentState(java.lang.Long id,
			java.util.HashMap<java.lang.String, com.ProcessDetails> stateDetails) {
		this.id = id;
		this.stateDetails = stateDetails;
	}

	public java.lang.String getTemp() {
		return this.temp;
	}

	public void setTemp(java.lang.String temp) {
		this.temp = temp;
	}

	public CurrentState(java.lang.Long id, java.lang.String temp) {
		this.id = id;
		this.temp = temp;
	}

}