package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class NodeDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "NODEDETAILS_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "NODEDETAILS_ID_GENERATOR", sequenceName = "NODEDETAILS_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Next Node")
	private java.lang.String nextNode;

	@org.kie.api.definition.type.Label(value = "Previous Node")
	private java.lang.String previousNode;

	public NodeDetails() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getNextNode() {
		return this.nextNode;
	}

	public void setNextNode(java.lang.String nextNode) {
		this.nextNode = nextNode;
	}

	public java.lang.String getPreviousNode() {
		return this.previousNode;
	}

	public void setPreviousNode(java.lang.String previousNode) {
		this.previousNode = previousNode;
	}

	public NodeDetails(java.lang.Long id, java.lang.String nextNode,
			java.lang.String previousNode) {
		this.id = id;
		this.nextNode = nextNode;
		this.previousNode = previousNode;
	}

}