package com;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class User  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private Integer age;
    
    @org.kie.api.definition.type.Position(value = 0)
    private String name;

    public User() {
    }

    public User(String name, Integer age) {
        this.name = name;
        this.age = age;
    }


    
    public Integer getAge() {
        return this.age;
    }

    public void setAge(  Integer age ) {
        this.age = age;
    }
    
    public String getName() {
        return this.name;
    }

    public void setName(  String name ) {
        this.name = name;
    }

    public String toString() {
        return "[Name="+name+", age="+age+"]";
    }


}